Repository NativeScript/nativescript-cli, pull requests merged in 2018-05, with the labels that each got.

#3556 fix: Support Node.js 10.x.x
  npm-shrinkwrap.json
  package.json
Labels: bug

#3557 fix(assets-generation): Do not fail in case some App_Resources are missing
  lib/services/project-data-service.ts
  test/services/project-data-service.ts
Labels: bug

#3562 fix: Build plugins when path to project has space
  lib/definitions/android-plugin-migrator.d.ts
  lib/services/android-plugin-build-service.ts
  test/services/android-plugin-build-service.ts
Labels: bug

#3580 fix(API): isValidNativeScriptProject returns incorrect result
  lib/services/project-service.ts
  test/project-service.ts
Labels: bug

#3589 fix: Tracking for used Debug tool is incorrect
  lib/services/debug-service.ts
  test/services/debug-service.ts
Labels: bug

#3592 fix(GDPR): Do not track local project paths
  lib/constants.ts
  lib/services/project-templates-service.ts
  lib/services/subscription-service.ts
  npm-shrinkwrap.json
  package.json
  test/project-templates-service.ts
  test/services/subscription-service.ts
Labels: bug

#3594 fix: Detect iOS devices connected by USB only
  npm-shrinkwrap.json
  package.json
Labels: bug

#3578 feat: Allow using JAVA 8+
  npm-shrinkwrap.json
  package.json
  vendor/gradle-plugin/build.gradle
  vendor/gradle-plugin/gradle/wrapper/gradle-wrapper.properties
Labels: feature

#3542 feat: Allow templates to be full applications
  lib/constants.ts
  lib/definitions/project.d.ts
  lib/services/project-service.ts
  lib/services/project-templates-service.ts
  test/project-service.ts
  test/project-templates-service.ts
  test/stubs.ts
Labels: feature

#3609 fix: Unable to fast sync changes with iOS runtime 4.0.1 and earlier
  lib/services/ios-debugger-port-service.ts
Labels: bug

#3608 fix: Unhandled rejection is thrown when disconnection iOS Device
  npm-shrinkwrap.json
  package.json
Labels: bug

#3623 fix(node-xcode): Update to 1.5.1 tag
  npm-shrinkwrap.json
  package.json
  test/ios-project-service.ts
Labels: bug, os: mac, unit testing

#3624 fix: platform remove command fails with old Android runtime
  lib/commands/remove-platform.ts
Labels: bug

#3628 fix: Device logs are not properly shown with debug command
  lib/services/android-debug-service.ts
  lib/services/ios-debug-service.ts
  test/services/android-debug-service.ts
  test/services/ios-debug-service.ts
Labels: bug

#3639 fix: TypeError is thrown when iOS device is detached during LiveSync
  npm-shrinkwrap.json
  package.json
Labels: bug

#3643 fix: Run and debug fail for iOS in Sidekick
  lib/definitions/debug.d.ts
  lib/definitions/ios-debugger-port-service.d.ts
  lib/definitions/ios-log-parser-service.d.ts
  lib/definitions/project.d.ts
  lib/services/ios-debug-service.ts
  lib/services/ios-debugger-port-service.ts
  lib/services/ios-log-parser-service.ts
  lib/services/livesync/android-livesync-service.ts
  lib/services/livesync/ios-device-livesync-service.ts
  lib/services/livesync/ios-livesync-service.ts
  lib/services/livesync/platform-livesync-service-base.ts
  test/services/ios-debugger-port-service.ts
  test/services/ios-log-parser-service.ts
Labels: bug, severity: critical

#3646 fix: Shrinkwrap is incorrect which prevents CLI from installing
  npm-shrinkwrap.json
Labels: bug

#3648 fix: `tns debug ios` fails to show chrome url
  npm-shrinkwrap.json
  package.json
Labels: bug, severity: critical

#3651 docs: Update Changelog for 4.1.0
  CHANGELOG.md
Labels: docs
