Repository NativeScript/nativescript-cli, pull requests merged in 2018-11, with the labels that each got.

#4050 feat() - [Yarn Support - Part 1 and 2] Yarn and Package Manager implementation
  lib/base-package-manager.ts
  lib/bootstrap.ts
  lib/commands/install.ts
  lib/commands/plugin/create-plugin.ts
  lib/commands/test-init.ts
  lib/common/commands/package-manager-set.ts
  lib/declarations.d.ts
  lib/node-package-manager.ts
  lib/options.ts
  lib/package-installation-manager.ts
  lib/package-manager.ts
  lib/services/android-plugin-build-service.ts
  lib/services/android-project-service.ts
  lib/services/extensibility-service.ts
  lib/services/init-service.ts
  lib/services/ios-debug-service.ts
  lib/services/nativescript-cloud-extension-service.ts
  lib/services/platform-service.ts
  lib/services/plugins-service.ts
  lib/services/prepare-platform-js-service.ts
  lib/services/project-service.ts
  lib/services/project-templates-service.ts
  lib/services/user-settings-service.ts
  lib/services/versions-service.ts
  lib/yarn-package-manager.ts
  test/debug.ts
  test/ios-project-service.ts
  test/nativescript-cli-lib.ts
  test/npm-installation-manager.ts
  test/npm-support.ts
  test/platform-commands.ts
  test/platform-service.ts
  test/plugin-create.ts
  test/plugins-service.ts
  test/project-service.ts
  test/project-templates-service.ts
  test/services/android-plugin-build-service.ts
  test/services/extensibility-service.ts
  test/services/ios-debug-service.ts
  test/services/pacote-service.ts
  test/stubs.ts
Labels: ♥ community PR

#4072 feat(): Add trailing newline when saving package.json
  lib/common/declarations.d.ts
  lib/common/file-system.ts
  npm-shrinkwrap.json
  package.json
Labels: ♥ community PR

#4078 fix: start log process on `tns debug ios --justlaunch` command
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/device-log-provider-base.ts
  lib/common/mobile/device-log-provider.ts
  lib/common/test/unit-tests/stubs.ts
  lib/services/ios-debug-service.ts
Labels: bug

#4073 fix: update natives, so CLI can work on Node.js 11
  npm-shrinkwrap.json
Labels: bug

#4133 fix(deps): update chokidar, so we can watch dirs with `(`
  npm-shrinkwrap.json
  package.json
Labels: bug

#4149 fix: fix yarn view method to return correct data
  lib/yarn-package-manager.ts
Labels: no-changelog

#4151 chore: rename npm-installation-manager file under test folder to package-installation-manager
  test/package-installation-manager.ts
Labels: no-changelog

#4161 fix: reset deviceLostTimer after clearing the device's timeout
  lib/services/livesync/playground/devices/preview-devices-service.ts
Labels: no-changelog

#4168 Docs for the public api for preview
  PublicAPI.md
Labels: docs

#4167 feat(preview-api): emit previewAppLiveSyncError when some error is thrown while livesyncing to preview app
  lib/definitions/preview-app-livesync.d.ts
  lib/services/livesync/livesync-service.ts
  lib/services/livesync/playground/preview-app-constants.ts
  lib/services/livesync/playground/preview-app-livesync-service.ts
Labels: feature

#4153 feat: improve analytics
  lib/bootstrap.ts
  lib/commands/debug.ts
  lib/common/commands/analytics.ts
  lib/common/commands/proxy/proxy-base.ts
  lib/common/declarations.d.ts
  lib/common/definitions/cli-global.d.ts
  lib/common/definitions/config.d.ts
  lib/common/definitions/eqatec-analytics.d.ts
  lib/common/definitions/eqatec.d.ts
  lib/common/services/analytics-service-base.ts
  lib/common/services/commands-service.ts
  lib/common/static-config-base.ts
  lib/common/test/unit-tests/analytics-service.ts
  lib/common/vendor/EqatecMonitor.min.js
  lib/config.ts
  lib/declarations.d.ts
  lib/definitions/platform.d.ts
  lib/helpers/livesync-command-helper.ts
  lib/options.ts
  lib/services/analytics/analytics-broker-process.ts
  lib/services/analytics/analytics-broker.ts
  lib/services/analytics/analytics-constants.ts
  lib/services/analytics/analytics-logging-service.ts
  lib/services/analytics/analytics-service.ts
  lib/services/analytics/analytics.d.ts
  lib/services/analytics/eqatec-analytics-provider.ts
  lib/services/analytics/google-analytics-provider.ts
  lib/services/doctor-service.ts
  lib/services/livesync/livesync-service.ts
  lib/services/platform-service.ts
  lib/services/project-templates-service.ts
  npm-shrinkwrap.json
  package.json
  test/commands/post-install.ts
  test/stubs.ts
Labels: feature

#4169 feat(package-manager): expose `package-manager get` command
  lib/bootstrap.ts
  lib/common/commands/package-manager-get.ts
Labels: no-changelog

#4177 fix(analytics): undefined file is created on every command
  lib/services/analytics/analytics-service.ts
Labels: bug

#4176 fix: builing of nativescript-cloud package fails
  lib/services/analytics/analytics-constants.d.ts
Labels: bug
