Repository NativeScript/nativescript-cli, pull requests merged in 2018-08, with the labels that each got.

#3791 fix: remove keys from package.json after project is created
  lib/constants.ts
  lib/services/project-service.ts
Labels: bug

#3793 fix: Unable to create project from local path of template v2
  lib/services/pacote-service.ts
Labels: bug

#3799 docs: update Changelog for 4.2.0
  CHANGELOG.md
Labels: docs

#3841 feat: use long living socket connection for sync
  lib/definitions/livesync.d.ts
  lib/services/livesync/android-device-livesync-sockets-service.ts
  lib/services/livesync/android-livesync-tool.ts
Labels: feature
