Repository NativeScript/nativescript-cli, pull requests merged in 2018-09, with the labels that each got.

#3868 fix: minor typo
  lib/services/livesync/android-livesync-tool.ts
Labels: bug

#3878 fix: prompter for mail on postinstall is very obligatory
  lib/constants.ts
  lib/services/subscription-service.ts
  test/services/subscription-service.ts
Labels: bug

#3882 fix: read npm registry from npm config
  lib/node-package-manager.ts
Labels: bug

#3895 docs: update Changelog for 4.2.4
  CHANGELOG.md
Labels: docs

#3910 fix: `tns platform add ios` should not be executed on non-macOS
  lib/commands/add-platform.ts
Labels: bug

#3900 fix: Project's Podfile is regenerated incorrectly
  lib/constants.ts
  lib/definitions/project.d.ts
  lib/services/cocoapods-service.ts
  lib/services/ios-project-service.ts
  test/cocoapods-service.ts
  test/ios-project-service.ts
Labels: bug

#3924 fix: native frameworks/code is added to tns_modules dir
  lib/tools/node-modules/node-modules-dest-copy.ts
Labels: bug

#3923 feat: remove requirement for Android Support Repository local installation
  lib/android-tools-info.ts
  lib/declarations.d.ts
  lib/services/android-plugin-build-service.ts
  lib/services/android-project-service.ts
  npm-shrinkwrap.json
  package.json
  test/stubs.ts
Labels: feature

#3933 fix: unable to create project from scoped package template
  lib/definitions/project.d.ts
  lib/services/project-templates-service.ts
  test/project-templates-service.ts
Labels: bug
