Repository NativeScript/nativescript-cli, pull requests merged in 2018-03, with the labels that each got.

#3406 feat(create): Keep pluginsData key from template's package.json
  lib/constants.ts
Labels: feature

#3419 fix: find correct apk name when --release passed
  lib/definitions/platform.d.ts
  lib/definitions/project.d.ts
  lib/services/android-project-service.ts
  lib/services/ios-project-service.ts
  lib/services/livesync/livesync-service.ts
  lib/services/platform-service.ts
  test/platform-commands.ts
  test/stubs.ts
Labels: in progress

#3427 docs: document run platform
  docs/man_pages/index.md
  docs/man_pages/project/configuration/prepare.md
  docs/man_pages/project/testing/run.md
Labels: docs

#3434 fix: pass devices for debugging correctly
  lib/commands/debug.ts
Labels: bug

#3443 fix: stop build twice for android
  lib/services/livesync/livesync-service.ts
Labels: bug

#3446 fix: pass all args to installapplication
  lib/services/platform-service.ts
Labels: bug

#3449 feat(analytics): Track Vue.js project type
  lib/project-data.ts
  test/project-data.ts
Labels: feature

#3460 fix: Do not print sysinfo if everything is fine
  lib/services/doctor-service.ts
Labels: bug

#3459 fix: Plugin remove command fails in case plugin name has dot
  lib/constants.ts
  lib/services/project-data-service.ts
  test/services/project-data-service.ts
Labels: bug

#3435 feat: introduce assets generation
  .vscode/launch.json
  PublicAPI.md
  docs/man_pages/project/configuration/resources/resources-generate-icons.md
  docs/man_pages/project/configuration/resources/resources-generate-splashes.md
  docs/man_pages/project/configuration/resources/resources-update.md
  lib/bootstrap.ts
  lib/commands/generate-assets.ts
  lib/constants.ts
  lib/declarations.d.ts
  lib/definitions/project.d.ts
  lib/options.ts
  lib/services/assets-generation/assets-generation-service.ts
  lib/services/project-data-service.ts
  npm-shrinkwrap.json
  package.json
  resources/assets/image-definitions.json
  test/image-generation-test.png
  test/nativescript-cli-lib.ts
  test/npm-installation-manager.ts
  test/project-service.ts
  test/services/project-data-service.ts
  test/stubs.ts
Labels: feature

#3504 docs: Fix the help of `tns generate splashes` command
  docs/man_pages/project/configuration/resources/resources-generate-splashes.md
Labels: bug, docs
