Repository NativeScript/nativescript-cli, pull requests merged in 2019-07, with the labels that each got.

#4788 fix: add package.json files from nativescript plugins to watch patterns
  lib/controllers/prepare-controller.ts
Labels: cla: yes

#4787 fix: release the console on deploy command
  lib/commands/deploy.ts
Labels: cla: yes

#4789 fix: fix prepare from plugin's directory
  lib/common/project-helper.ts
Labels: cla: yes

#4791 fix: update dependencies to latest rc versions
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4790 fix: handle preview issues
  lib/controllers/prepare-controller.ts
  lib/controllers/preview-app-controller.ts
  lib/services/livesync/playground/preview-qr-code-service.ts
Labels: bug, cla: yes

#4793 refactor(migrate): bump the version of {N} vue to 2.3.0-rc.1
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4794 fix: fix stop run on device when the method is called with empty array
  lib/controllers/run-controller.ts
  test/controllers/run-controller.ts
Labels: cla: yes

#4786 fix: don't restart application when lazy loaded code is changed in angular app with uglify option
  lib/services/webpack/webpack-compiler-service.ts
  lib/services/webpack/webpack.d.ts
Labels: cla: yes

#4795 fix: update the version of nativescript-dev-webpack plugin on migrate command
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4799 chore: merge release in master
  lib/commands/deploy.ts
  lib/common/project-helper.ts
  lib/controllers/migrate-controller.ts
  lib/controllers/prepare-controller.ts
  lib/controllers/preview-app-controller.ts
  lib/controllers/run-controller.ts
  lib/services/livesync/playground/preview-qr-code-service.ts
  lib/services/webpack/webpack-compiler-service.ts
  lib/services/webpack/webpack.d.ts
  test/controllers/run-controller.ts
Labels: cla: yes

#4802 fix: preview and run do not work correctly
  lib/controllers/prepare-controller.ts
  lib/controllers/preview-app-controller.ts
  lib/services/ios-log-filter.ts
Labels: bug, cla: yes

#4796 feat: validate the version of nativescript-dev-webpack plugin on every command
  lib/commands/build.ts
  lib/commands/debug.ts
  lib/commands/deploy.ts
  lib/commands/preview.ts
  lib/common/mobile/mobile-core/devices-service.ts
  lib/controllers/prepare-controller.ts
  lib/helpers/livesync-command-helper.ts
  lib/services/project-changes-service.ts
  test/controllers/prepare-controller.ts
Labels: cla: yes

#4805 fix: iOS device logs are not using source maps initially
  lib/services/livesync/ios-livesync-service.ts
Labels: bug, cla: yes, os: ios

#4807 fix: migrate command failure should be handled correctly
  lib/controllers/migrate-controller.ts
Labels: bug, cla: yes

#4808 fix: show the actual error when hook fails
  lib/common/services/hooks-service.ts
Labels: bug, cla: yes

#4809 fix: make the update command behave similar to the logic before 6.0.0
  lib/controllers/update-controller.ts
  lib/package-manager.ts
Labels: cla: yes

#4811 fix: migrate fails when karma.config.js is missing
  lib/controllers/migrate-controller.ts
Labels: bug, cla: yes, unit testing

#4806 fix: fix issues with Sidekick, cloud builds and multiple projects/devices
  lib/controllers/build-controller.ts
  lib/controllers/run-controller.ts
  lib/services/platform/prepare-native-platform-service.ts
Labels: cla: yes

#4810 fix: fix cloud deploy command
  lib/common/mobile/mobile-core/devices-service.ts
  lib/controllers/deploy-controller.ts
  lib/definitions/run.d.ts
  lib/helpers/deploy-command-helper.ts
  lib/helpers/livesync-command-helper.ts
Labels: cla: yes

#4816 Improve the `migrate` command based on the feedback
  lib/controllers/migrate-controller.ts
  lib/definitions/migrate.d.ts
  lib/definitions/project.d.ts
  lib/project-data.ts
  lib/services/project-data-service.ts
  test/options.ts
  test/services/project-data-service.ts
  test/stubs.ts
Labels: cla: yes

#4817 fix: fix preview from Sidekick
  lib/controllers/preview-app-controller.ts
Labels: cla: yes

#4823 fix: add skipNativePrepare to buildData
  lib/helpers/deploy-command-helper.ts
Labels: cla: yes

#4819 fix: build output location not printed
  lib/controllers/build-controller.ts
Labels: cla: yes

#4826 fix: execute npm install before all hooks
  lib/controllers/prepare-controller.ts
  lib/services/webpack/webpack-compiler-service.ts
Labels: bug, cla: yes

#4827 fix: `tns debug ios` should work on device
  lib/common/mobile/ios/device/ios-application-manager.ts
Labels: bug, cla: yes, severity: critical

#4829 fix: final Update and Migrate improvements
  lib/controllers/migrate-controller.ts
  lib/controllers/update-controller-base.ts
  lib/controllers/update-controller.ts
  lib/declarations.d.ts
  lib/definitions/migrate.d.ts
  lib/services/android-resources-migration-service.ts
Labels: cla: yes

#4830 docs: introduce help for migrate command
  docs/man_pages/general/migrate.md
  docs/man_pages/general/package-manager-get.md
  docs/man_pages/general/package-manager-set.md
  docs/man_pages/general/update.md
  docs/man_pages/general/usage-reporting.md
  docs/man_pages/index.md
Labels: cla: yes

#4824 feat: show error when the project is not migrated and is not compatible for 6.0 release
  lib/bootstrap.ts
  lib/commands/build.ts
  lib/commands/debug.ts
  lib/commands/migrate.ts
  lib/commands/prepare.ts
  lib/commands/preview.ts
  lib/commands/run.ts
  lib/commands/test.ts
  lib/controllers/migrate-controller.ts
  lib/controllers/prepare-controller.ts
  lib/definitions/migrate.d.ts
  lib/helpers/bundle-validator-helper.ts
  test/controllers/prepare-controller.ts
  test/helpers/bundle-validator-helper.ts
Labels: cla: yes

#4832 fix: show warning for less only when the project has nativescript-dev-less plugin as dependency
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4834 fix: migrate validation issues
  lib/commands/build.ts
  lib/commands/debug.ts
  lib/commands/migrate.ts
  lib/commands/prepare.ts
  lib/commands/preview.ts
  lib/commands/run.ts
  lib/commands/test.ts
  lib/commands/update.ts
  lib/controllers/migrate-controller.ts
  lib/definitions/migrate.d.ts
  test/update.ts
Labels: cla: yes

#4837 fix: add the link to blog post
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4836 fix: don't build every time the application from sidekick when using cloud build
  lib/services/project-changes-service.ts
Labels: cla: yes

#4839 Kddimitrov/fix update invalid tag
  docs/man_pages/general/update.md
  docs/man_pages/project/configuration/update.md
  lib/controllers/update-controller-base.ts
  lib/controllers/update-controller.ts
Labels: cla: yes

#4840 fix: disable the `watch` in release builds as its triggering 2 snapshot generations
  lib/helpers/livesync-command-helper.ts
Labels: cla: yes

#4841 chore: update migrate dependencies
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4843 fix: fix the missing icons in newly created apps on iOS devices
  lib/services/platform/add-platform-service.ts
Labels: cla: yes

#4848 feat: skip migration check based on --force
  lib/commands/build.ts
  lib/commands/debug.ts
  lib/commands/prepare.ts
  lib/commands/preview.ts
  lib/commands/run.ts
  lib/commands/test.ts
  lib/controllers/migrate-controller.ts
  lib/declarations.d.ts
  lib/services/platform/platform-validation-service.ts
Labels: cla: yes

#4847 fix: stop all webpack processes from sidekick when stopping the livesync
  lib/controllers/run-controller.ts
  lib/definitions/livesync.d.ts
  lib/services/livesync-process-data-service.ts
Labels: cla: yes

#4851 chore: merge release in master
  docs/man_pages/general/migrate.md
  docs/man_pages/general/package-manager-get.md
  docs/man_pages/general/package-manager-set.md
  docs/man_pages/general/update.md
  docs/man_pages/general/usage-reporting.md
  docs/man_pages/index.md
  docs/man_pages/project/configuration/update.md
  lib/bootstrap.ts
  lib/commands/build.ts
  lib/commands/debug.ts
  lib/commands/deploy.ts
  lib/commands/migrate.ts
  lib/commands/prepare.ts
  lib/commands/preview.ts
  lib/commands/run.ts
  lib/commands/test.ts
  lib/commands/update.ts
  lib/common/mobile/ios/device/ios-application-manager.ts
  lib/common/mobile/mobile-core/devices-service.ts
  lib/common/services/hooks-service.ts
  lib/controllers/build-controller.ts
  lib/controllers/deploy-controller.ts
  lib/controllers/migrate-controller.ts
  lib/controllers/prepare-controller.ts
  lib/controllers/preview-app-controller.ts
  lib/controllers/run-controller.ts
  lib/controllers/update-controller-base.ts
  lib/controllers/update-controller.ts
  lib/declarations.d.ts
  lib/definitions/livesync.d.ts
  lib/definitions/migrate.d.ts
  lib/definitions/project.d.ts
  lib/definitions/run.d.ts
  lib/helpers/bundle-validator-helper.ts
  lib/helpers/deploy-command-helper.ts
  lib/helpers/livesync-command-helper.ts
  lib/package-manager.ts
  lib/project-data.ts
  lib/services/android-resources-migration-service.ts
  lib/services/ios-log-filter.ts
  lib/services/livesync-process-data-service.ts
  lib/services/livesync/ios-livesync-service.ts
  lib/services/platform/add-platform-service.ts
  lib/services/platform/platform-validation-service.ts
  lib/services/platform/prepare-native-platform-service.ts
  lib/services/project-changes-service.ts
  lib/services/project-data-service.ts
  lib/services/webpack/webpack-compiler-service.ts
  test/helpers/bundle-validator-helper.ts
  test/options.ts
  test/services/project-data-service.ts
  test/stubs.ts
  test/update.ts
Labels: cla: yes

#4849 fix: start native watch on cloud run command and from sidekick when cloud build is selected
  lib/controllers/prepare-controller.ts
Labels: bug, cla: yes, severity: critical

#4852 fix: update Angular deps during app migration
  lib/controllers/migrate-controller.ts
  lib/definitions/migrate.d.ts
Labels: cla: yes

#4854 fix: support node <= 8.9.4 (lookbehind is supported only with the `harmony` flag)
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4850 docs: --no-hmr added, --syncAllFiles and --bundle removed, added note…
  docs/man_pages/project/configuration/prepare.md
  docs/man_pages/project/testing/build-android.md
  docs/man_pages/project/testing/build-ios.md
  docs/man_pages/project/testing/build.md
  docs/man_pages/project/testing/debug-android.md
  docs/man_pages/project/testing/debug-ios.md
  docs/man_pages/project/testing/debug.md
  docs/man_pages/project/testing/preview.md
  docs/man_pages/project/testing/run-android.md
  docs/man_pages/project/testing/run-ios.md
  docs/man_pages/project/testing/run.md
  docs/man_pages/project/testing/test.md
Labels: cla: yes

#4855 docs: update `tns migrate` docs based on the latest changes
  docs/man_pages/general/migrate.md
  docs/man_pages/project/configuration/prepare.md
  docs/man_pages/project/testing/build-android.md
  docs/man_pages/project/testing/build-ios.md
  docs/man_pages/project/testing/build.md
  docs/man_pages/project/testing/debug-android.md
  docs/man_pages/project/testing/debug-ios.md
  docs/man_pages/project/testing/preview.md
  docs/man_pages/project/testing/run-android.md
  docs/man_pages/project/testing/run-ios.md
  docs/man_pages/project/testing/run.md
  docs/man_pages/project/testing/test-android.md
  docs/man_pages/project/testing/test-ios.md
Labels: cla: yes

#4857 fix: don't override `--env.production` and `--env.verbose` when provided from user
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4858 docs: update outdated docs
  docs/man_pages/index.md
  docs/man_pages/lib-management/plugin-add.md
  docs/man_pages/lib-management/plugin-create.md
  docs/man_pages/lib-management/plugin-remove.md
  docs/man_pages/lib-management/plugin-update.md
  docs/man_pages/project/configuration/platform-add.md
  docs/man_pages/project/configuration/prepare.md
  docs/man_pages/project/creation/create.md
  docs/man_pages/project/testing/build-android.md
Labels: cla: yes

#4859 docs: remove --sdk flag from documentation
  docs/man_pages/project/configuration/platform-add.md
Labels: cla: yes

#4860 fix: preview for app downloaded from playground fails
  lib/controllers/preview-app-controller.ts
  test/services/playground/preview-app-livesync-service.ts
Labels: bug, cla: yes, preview

#4862 chore: update required deps for 6.0
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4866 chore: update Changelog for 6.0 release
  CHANGELOG.md
Labels: cla: yes

#4868 fix: bump the version of `nativescript-unit-test-runner` from migrate
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4870 chore: set version to 6.0.1
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#4871 fix: fix issues when stopping the livesync process
  lib/controllers/run-controller.ts
Labels: cla: yes

#4872 fix: fix the behavior when ddi is not installed on iOS device
  lib/controllers/run-controller.ts
Labels: bug, cla: yes, os: ios, os: windows

#4869 fix: add forgotten migrate dependencies for Vue and Angular apps
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4856 fix: respect correctly `hmr: false` from command's dashed options
  lib/common/definitions/yargs.d.ts
  lib/common/services/commands-service.ts
  lib/options.ts
  npm-shrinkwrap.json
  package.json
  test/options.ts
Labels: cla: yes

#4875 docs: remove --platform-template from CLI's help
  docs/man_pages/project/configuration/platform-add.md
Labels: bug, cla: yes

#4880 fix: parse options correctly
  lib/options.ts
  test/options.ts
Labels: cla: yes

#4881 docs: update migrate help and changelog for 6.0.1
  CHANGELOG.md
  docs/man_pages/general/migrate.md
Labels: cla: yes

#4886 fix: migrate and update exit with code 0 when everything is up-to-date
  lib/commands/migrate.ts
  lib/commands/update.ts
Labels: cla: yes

#4888 fix: multiple errors in Sidekick
  lib/controllers/prepare-controller.ts
  lib/controllers/preview-app-controller.ts
  lib/controllers/run-controller.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/services/webpack/webpack-compiler-service.ts
  npm-shrinkwrap.json
  package.json
  test/controllers/run-controller.ts
Labels: bug, cla: yes, debug, preview, run

#4887 fix(migrate): include forgotten Angular dependency from the code-sharing apps
  docs/man_pages/general/migrate.md
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4890 docs: changelog for 6.0.2
  CHANGELOG.md
Labels: cla: yes

#4891 Merge release into master
  CHANGELOG.md
  docs/man_pages/general/migrate.md
  docs/man_pages/index.md
  docs/man_pages/lib-management/plugin-add.md
  docs/man_pages/lib-management/plugin-create.md
  docs/man_pages/lib-management/plugin-remove.md
  docs/man_pages/lib-management/plugin-update.md
  docs/man_pages/project/configuration/platform-add.md
  docs/man_pages/project/configuration/prepare.md
  docs/man_pages/project/creation/create.md
  docs/man_pages/project/testing/build-android.md
  docs/man_pages/project/testing/build-ios.md
  docs/man_pages/project/testing/build.md
  docs/man_pages/project/testing/debug-android.md
  docs/man_pages/project/testing/debug-ios.md
  docs/man_pages/project/testing/debug.md
  docs/man_pages/project/testing/preview.md
  docs/man_pages/project/testing/run-android.md
  docs/man_pages/project/testing/run-ios.md
  docs/man_pages/project/testing/run.md
  docs/man_pages/project/testing/test-android.md
  docs/man_pages/project/testing/test-ios.md
  docs/man_pages/project/testing/test.md
  lib/commands/migrate.ts
  lib/commands/update.ts
  lib/common/definitions/yargs.d.ts
  lib/common/services/commands-service.ts
  lib/controllers/migrate-controller.ts
  lib/controllers/prepare-controller.ts
  lib/controllers/preview-app-controller.ts
  lib/controllers/run-controller.ts
  lib/definitions/migrate.d.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/options.ts
  lib/services/webpack/webpack-compiler-service.ts
  npm-shrinkwrap.json
  package.json
  test/controllers/run-controller.ts
  test/options.ts
  test/services/playground/preview-app-livesync-service.ts
Labels: cla: yes

#4901 fix: missing --template arg
  docs/man_pages/project/creation/create.md
Labels: cla: yes

#4903 fix: ability to publish iOS applications for users with two-factor authentication enabled
  docs/man_pages/publishing/apple-login.md
  docs/man_pages/publishing/appstore-upload.md
  docs/man_pages/publishing/publish-ios.md
  lib/bootstrap.ts
  lib/commands/apple-login.ts
  lib/commands/appstore-list.ts
  lib/commands/appstore-upload.ts
  lib/common/constants.ts
  lib/common/http-client.ts
  lib/declarations.d.ts
  lib/options.ts
  lib/services/apple-portal/apple-portal-application-service.ts
  lib/services/apple-portal/apple-portal-cookie-service.ts
  lib/services/apple-portal/apple-portal-session-service.ts
  lib/services/apple-portal/definitions.d.ts
  lib/services/itmstransporter-service.ts
  test/tns-appstore-upload.ts
Labels: bug, cla: yes

#4912 fix: hardcode karma-webpack to 3.0.5
  config/test-dependencies.json
Labels: bug, cla: yes

#4915 fix: fix appstore list command for accounts with 2fa
  lib/commands/appstore-upload.ts
  lib/services/apple-portal/apple-portal-session-service.ts
  lib/services/apple-portal/definitions.d.ts
Labels: bug, cla: yes, no-changelog
