Repository NativeScript/nativescript-cli, pull requests merged in 2019-02, with the labels that each got.

#4331 fix: incorrect filtering of Android logs by tag
  lib/common/mobile/android/android-log-filter.ts
  lib/common/test/unit-tests/android-log-filter.ts
Labels: bug

#4334 fix: missing logs when `__enableVerboseLogging` is called
  lib/common/mobile/android/android-log-filter.ts
  lib/common/test/unit-tests/android-log-filter.ts
Labels: bug, no-changelog, os: android

#4335 chore: clean-up code used for Node.js 4 and 5
  .vscode/launch.json
  bin/tns
  lib/common/scripts/node-args.js
  lib/common/test-scripts/istanbul.js
  lib/common/test-scripts/mocha.js
  package.json
  postinstall.js
  preuninstall.js
  test-scripts/istanbul.js
  test-scripts/mocha.js
  test/nativescript-cli-lib.ts
Labels: no-changelog, technical debt

#4342 fix: objective-C source code not added from App Resources
  lib/services/ios-project-service.ts
Labels: bug

#4336 chore: fix travis build of next/rc/release-patch versions
  .gitignore
  .npmignore
  .travis.yml
  Gruntfile.js
Labels: no-changelog

#4352 fix: set correct versions in plugin's build.gradle
  vendor/gradle-plugin/build.gradle
Labels: bug, severity: critical

#4358 docs: update CHANGELOG for 5.2.0
  CHANGELOG.md
Labels: docs

#4359 fix: cli's local adb is not used
  lib/config.ts
Labels: bug, no-changelog

#4363 chore: skip tns_modules cleanup from CLI
  lib/definitions/platform.d.ts
  lib/tools/node-modules/node-modules-builder.ts
  test/npm-support.ts
Labels: technical debt

#4332 fix: remove duplicated platforms from project's podfile
  lib/bootstrap.ts
  lib/definitions/project.d.ts
  lib/services/cocoapods-platform-manager.ts
  lib/services/cocoapods-service.ts
  lib/services/ios-project-service.ts
  test/cocoapods-service.ts
  test/ios-project-service.ts
Labels: bug, new PR

#4386 fix: show warning when the platform's version in project's podfile will be replaced with another platform's version
  lib/services/cocoapods-platform-manager.ts
Labels: bug, new PR, no-changelog

#4385 fix: process correctly podfiles without platform's version
  lib/services/cocoapods-platform-manager.ts
  test/cocoapods-service.ts
Labels: bug, new PR, no-changelog

#4381 fix: validate test init before executing the test command
  lib/commands/test.ts
  lib/common/declarations.d.ts
  lib/common/errors.ts
  lib/definitions/project.d.ts
  lib/services/test-execution-service.ts
  test/services/test-execution-serice.ts
  test/stubs.ts
Labels: new PR

#4395 fix: add new line at the end of the platform's section in order to remove it correctly
  lib/services/cocoapods-platform-manager.ts
  test/cocoapods-service.ts
Labels: bug, new PR

#4397 chore: improve unit tests
  resources/test/plugin-with-scoped-dependency.zip
  test/npm-support.ts
  test/project-service.ts
  test/tools/node-modules/node-modules-dependencies-builder.ts
Labels: new PR

#4396 fix: ensure a single web client connected for debugging
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/ios/device/ios-application-manager.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
  lib/common/services/lock-service.ts
  lib/common/test/unit-tests/stubs.ts
  lib/definitions/lock-service.d.ts
  lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
  lib/services/livesync/ios-device-livesync-service.ts
Labels: cla: yes, new PR

#4404 fix: errors from `tns doctor` are not visible in CI environment
  lib/common/helpers.ts
  lib/common/test/unit-tests/helpers.ts
  test/services/doctor-service.ts
  test/services/platform-environment-requirements.ts
Labels: bug, ci, cla: yes, new PR

#4405 fix: increase the debugger port timeout in order to support bigger apps
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/services/lock-service.ts
  lib/constants.ts
  lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
  lib/services/ios-debugger-port-service.ts
  test/services/ios-debugger-port-service.ts
Labels: cla: yes, new PR

#4406 fix: update node-xcode library
  lib/services/ios-project-service.ts
  npm-shrinkwrap.json
  package.json
  test/ios-project-service.ts
Labels: cla: yes, new PR
