Repository NativeScript/nativescript-cli, pull requests merged in 2019-08, with the labels that each got.

#4917 fix: avoid getting crashed LiveSync when the fast sync fails
  lib/commands/test.ts
  lib/controllers/run-controller.ts
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#4907 feat: Support .xcframework bundles
  lib/definitions/platform.d.ts
  lib/services/android-project-service.ts
  lib/services/ios-project-service.ts
  test/platform-commands.ts
  test/stubs.ts
Labels: cla: yes

#4895 feat: add support for Android SDK 29 for compilation
  lib/android-tools-info.ts
  lib/declarations.d.ts
  lib/definitions/android-plugin-migrator.d.ts
  lib/services/android-plugin-build-service.ts
  lib/services/android-project-service.ts
  lib/services/android/gradle-build-args-service.ts
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#4946 chore: bump version to 6.0.4
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#4925 fix: include all chunkFiles in fallbackFiles in order to avoid wrong lazy Angular chunks
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4949 chore: merge release in master
  CHANGELOG.md
  config/test-dependencies.json
  docs/man_pages/project/creation/create.md
  docs/man_pages/publishing/apple-login.md
  docs/man_pages/publishing/appstore-upload.md
  docs/man_pages/publishing/publish-ios.md
  lib/bootstrap.ts
  lib/commands/apple-login.ts
  lib/commands/appstore-list.ts
  lib/commands/appstore-upload.ts
  lib/commands/test.ts
  lib/common/constants.ts
  lib/common/http-client.ts
  lib/controllers/run-controller.ts
  lib/declarations.d.ts
  lib/options.ts
  lib/services/apple-portal/apple-portal-application-service.ts
  lib/services/apple-portal/apple-portal-cookie-service.ts
  lib/services/apple-portal/apple-portal-session-service.ts
  lib/services/apple-portal/definitions.d.ts
  lib/services/itmstransporter-service.ts
  lib/services/webpack/webpack-compiler-service.ts
  test/tns-appstore-upload.ts
Labels: cla: yes

#4950 fix(ios): isDynamicFramework check for `.xcframework`s
  lib/services/ios-project-service.ts
Labels: cla: yes

#4948 feat: support Xcode 11 and iOS 13
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#4953 fix: "improve this" btn doesn't work for CLI docs
  docs/build-jekyll-md.sh
  docs/man_pages/index.html
  docs/man_pages/start.md
  lib/common/services/help-service.ts
  lib/common/test/unit-tests/services/help-service.ts
Labels: cla: yes

#4955 fix: add missing await for isDynamicFramework check
  lib/services/ios-project-service.ts
Labels: bug, cla: yes

#4960 fix: remove usages of logger.out in CLI code
  lib/common/errors.ts
  lib/common/test/unit-tests/errors.ts
  lib/common/test/unit-tests/stubs.ts
  test/stubs.ts
Labels: cla: yes

#4962 fix: certificates and provision parsing should work on macOS Catalina
  npm-shrinkwrap.json
  package.json
Labels: bug, cla: yes

#4961 feat: add tracking for React and Svelte projecs
  lib/constants.ts
  lib/controllers/update-controller.ts
  lib/project-data.ts
  test/controllers/update-controller.ts
  test/project-data.ts
Labels: cla: yes, feature

#4965 feat(publish): ability to publish applications using Xcode 11
  lib/commands/appstore-upload.ts
  lib/common/services/xcode-select-service.ts
  lib/common/test/unit-tests/xcode-select-service.ts
  lib/declarations.d.ts
  lib/services/itmstransporter-service.ts
  test/tns-appstore-upload.ts
Labels: cla: yes

#4973 feat: open feedback form when CLI is uninstalled
  lib/common/commands/preuninstall.ts
  lib/common/test/unit-tests/preuninstall.ts
  lib/constants.ts
Labels: cla: yes, feature

#4981 fix: tns update will not modify webpack.config.js of React/Svelte projects
  lib/controllers/update-controller.ts
Labels: bug, cla: yes

#4983 fix: open feedback form on preuninstall
  preuninstall.js
  test/preuninstall.ts
Labels: bug, cla: yes

#4979 docs: update privacy policy message based on the latest legal updates
  lib/constants.ts
  lib/services/subscription-service.ts
  test/services/subscription-service.ts
Labels: cla: yes

#4972 fix: speed up the prepare process
  lib/common/helpers.ts
  lib/declarations.d.ts
  lib/services/cocoapods-service.ts
  lib/services/xcconfig-service.ts
  lib/services/xcproj-service.ts
  test/cocoapods-service.ts
Labels: cla: yes

#4986 fix: aab name changed to include build mode(debug, release)
  lib/services/android-project-service.ts
Labels: cla: yes

#4988 chore: update doctor version
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#4989 fix: ensure data is sent to analytics on preuninstall
  lib/common/commands/preuninstall.ts
  lib/common/declarations.d.ts
  lib/common/test/unit-tests/preuninstall.ts
  lib/detached-processes/detached-process-enums.d.ts
  lib/services/analytics/analytics-broker-process.ts
  lib/services/analytics/analytics-service.ts
  preuninstall.js
  test/preuninstall.ts
Labels: bug, cla: yes

#4990 fix: update messages on postinstall
  lib/commands/post-install.ts
Labels: cla: yes

#4992 fix(npm/pacote): allow tns to be able to use npm configuration properly
  lib/bootstrap.ts
  lib/declarations.d.ts
  lib/definitions/libnpmconfig.d.ts
  lib/services/npm-config-service.ts
  lib/services/pacote-service.ts
  npm-shrinkwrap.json
  package.json
  test/services/pacote-service.ts
Labels: cla: yes

#4967 feat: support LiveSync to Wi-Fi devices
  lib/common/commands/device/list-devices.ts
  lib/common/constants.ts
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/android/android-device.ts
  lib/common/mobile/android/android-virtual-device-service.ts
  lib/common/mobile/android/genymotion/genymotion-service.ts
  lib/common/mobile/device-emitter.ts
  lib/common/mobile/ios/device/ios-device-operations.ts
  lib/common/mobile/ios/device/ios-device.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/mobile/ios/simulator/ios-emulator-services.ts
  lib/common/mobile/ios/simulator/ios-simulator-device.ts
  lib/common/mobile/mobile-core/device-discovery.ts
  lib/common/mobile/mobile-core/devices-service.ts
  lib/common/mobile/mobile-core/ios-device-discovery.ts
  lib/common/test/unit-tests/mobile/android-emulator-service.ts
  lib/common/test/unit-tests/mobile/android-virtual-device-service.ts
  lib/common/test/unit-tests/mobile/devices-service.ts
  lib/common/test/unit-tests/mobile/genymotion/genymotion-service.ts
  lib/common/test/unit-tests/mobile/ios-simulator-discovery.ts
  lib/constants.ts
  lib/declarations.d.ts
  lib/device-sockets/ios/notification.ts
  lib/device-sockets/ios/socket-request-executor.ts
  lib/services/hmr-status-service.ts
  lib/services/ios-device-debug-service.ts
  lib/services/livesync/ios-device-livesync-service.ts
  npm-shrinkwrap.json
  package.json
  test/services/livesync/android-device-livesync-service-base.ts
Labels: cla: yes

#4984 feat: add tracking in analytics for company using NativeScript CLI
  config/config.json
  lib/bootstrap.ts
  lib/common/declarations.d.ts
  lib/common/definitions/json-file-settings-service.d.ts
  lib/common/definitions/user-settings.d.ts
  lib/common/services/analytics/google-analytics-custom-dimensions.d.ts
  lib/common/services/json-file-settings-service.ts
  lib/common/services/user-settings-service.ts
  lib/common/test/unit-tests/services/json-file-settings-service.ts
  lib/common/test/unit-tests/yok.ts
  lib/common/yok.ts
  lib/config.ts
  lib/controllers/company-insights-controller.ts
  lib/declarations.d.ts
  lib/definitions/company-insights-controller.d.ts
  lib/definitions/ip-service.d.ts
  lib/services/analytics-settings-service.ts
  lib/services/analytics/analytics-service.ts
  lib/services/analytics/google-analytics-provider.ts
  lib/services/ip-service.ts
  lib/services/user-settings-service.ts
  npm-shrinkwrap.json
  test/controllers/company-insights-controller.ts
  test/nativescript-cli-lib.ts
  test/services/ip-service.ts
Labels: cla: yes

#4994 fix: save and remove of user-settings are not working
  lib/services/user-settings-service.ts
  test/services/user-settings-service.ts
Labels: bug, cla: yes

#4997 fix: remove local caching of getting company data
  lib/controllers/company-insights-controller.ts
  test/config/config-json.ts
  test/controllers/company-insights-controller.ts
Labels: cla: yes

#4998 fix: list of apps is not working for iOS Devices
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#4999 chore: bump version to 6.2.0
  npm-shrinkwrap.json
  package.json
Labels: cla: yes
