Repository NativeScript/nativescript-cli, pull requests merged in 2019-11, with the labels that each got.

#5108 chore: create changelog for 6.2.0 release
  CHANGELOG.md
Labels: cla: yes

#5121 fix: values-v<sdk> directories are not prepared correctly
  lib/services/android-project-service.ts
  test/services/android-project-service.ts
Labels: bug, cla: yes

#5130 chore: merge release-patch in release
  lib/controllers/migrate-controller.ts
  lib/services/webpack/webpack-compiler-service.ts
  npm-shrinkwrap.json
  package.json
Labels: cla: yes

#5137 fix: fix livesync when `--no-hmr` option is provided and changes are reverted to the initial state of application
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes, no-changelog

#5129 feat: support for node v13
  package.json
Labels: cla: yes

#5144 chore: create changelog for 6.2.1 release
  CHANGELOG.md
Labels: cla: yes

#5139 fix: generate iOS images when we have their sizes
  lib/services/project-data-service.ts
  npm-shrinkwrap.json
  package.json
  resources/assets/image-definitions.json
  test/services/project-data-service.ts
Labels: bug, cla: yes, resources generation

#5148 fix: update scoped core package
  lib/constants.ts
  lib/controllers/update-controller.ts
Labels: cla: yes

#5146 fix: update requires migrate for invalid versions
  lib/commands/update.ts
Labels: cla: yes

#5152 chore: add script for automatic changelog generation
  .npmignore
  generate_changelog.js
Labels: cla: yes

#5098 feat: reduce HMR crashes in Preview and recover properly after them
  lib/controllers/preview-app-controller.ts
  lib/controllers/run-controller.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/services/livesync/playground/preview-sdk-service.ts
  lib/services/log-parser-service.ts
  test/services/ios-debugger-port-service.ts
  test/services/log-parser-service.ts
Labels: cla: yes, e2e test needed

#5151 `tns test init --help` doesn't show the available unit testing frameworks
  docs/man_pages/project/testing/test-init.md
  lib/common/services/micro-templating-service.ts
  lib/common/test/unit-tests/services/help-service.ts
  lib/definitions/project.d.ts
  lib/services/test-initialization-service.ts
Labels: bug, cla: yes

#5157 chore: Update CHANGELOG.md
  CHANGELOG.md
Labels: cla: yes

#5156 feat: improve the transition from preview to run command
  lib/services/livesync/playground/preview-app-plugins-service.ts
  test/services/playground/preview-app-plugins-service.ts
Labels: cla: yes, feature

#5147 Updated documentation for cloud builds
  docs/man_pages/cloud/cloud-setup.md
Labels: cla: yes

#5165 chore: merge release in master
  .npmignore
  CHANGELOG.md
  generate_changelog.js
  lib/controllers/migrate-controller.ts
  lib/services/android-project-service.ts
  lib/services/project-data-service.ts
  lib/services/webpack/webpack-compiler-service.ts
  resources/assets/image-definitions.json
  test/services/android-project-service.ts
  test/services/project-data-service.ts
Labels: cla: yes
