Repository NativeScript/nativescript-cli, pull requests merged in 2019-05, with the labels that each got.

#4573 fix: logcat process is not restarted in some cases
  lib/common/mobile/android/logcat-helper.ts
  lib/common/test/unit-tests/mobile/android/logcat-helper.ts
Labels: bug, cla: yes, new PR, os: android

#4577 chore: merge release into master
  CHANGELOG.md
  lib/declarations.d.ts
  lib/services/cocoapods-service.ts
  lib/services/ios-project-service.ts
  lib/services/xcconfig-service.ts
  test/ios-project-service.ts
Labels: cla: yes, new PR

#4581 feat: allow executing JS funcitons on cleanup
  lib/definitions/cleanup-service.d.ts
  lib/detached-processes/cleanup-js-subprocess.ts
  lib/detached-processes/cleanup-process-definitions.d.ts
  lib/detached-processes/cleanup-process.ts
  lib/detached-processes/detached-process-enums.d.ts
  lib/services/cleanup-service.ts
Labels: cla: yes, new PR, no-changelog

#4578 feat: show deprecated messages for things that will be dropped as of NativeScript v.6.0.0
  lib/commands/clean-app.ts
  lib/common/services/commands-service.ts
  lib/declarations.d.ts
  lib/options.ts
  lib/services/platform-service.ts
  test/platform-service.ts
Labels: cla: yes, new PR

#4568 Kddimitrov/watch app
  lib/bootstrap.ts
  lib/constants.ts
  lib/definitions/project.d.ts
  lib/definitions/xcode.d.ts
  lib/services/ios-extensions-service.ts
  lib/services/ios-native-target-service-base.ts
  lib/services/ios-project-service.ts
  lib/services/ios-watch-app-service.ts
  npm-shrinkwrap.json
  package.json
  test/ios-project-service.ts
Labels: cla: yes, new PR

#4588 chore: remove the deprecation message for `--bundle` option
  lib/options.ts
Labels: new PR, no-changelog

#4563 docs: remove obsolete HMR steps
  docs/man_pages/project/testing/debug-android.md
Labels: cla: yes, new PR

#4590 chore: update watchapp beta warning
  lib/services/ios-project-service.ts
Labels: new PR

#4594 fix: target argument passed to xcodebuild when using workspace
  lib/services/ios-project-service.ts
Labels: cla: yes, new PR

#4597 fix (test command): generate source maps when debug-brk is set
  lib/services/test-execution-service.ts
  resources/test/karma.conf.js
Labels: cla: yes, new PR

#4599 fix: ensure analytics and cleanup processes are not leaking
  lib/detached-processes/cleanup-process.ts
  lib/services/analytics/analytics-broker-process.ts
Labels: bug, new PR

#4600 fix: do not use HMR when debugBrk is set as we will restart the app on each LiveSync
  lib/options.ts
Labels: new PR

#4601 fix: logger changes broke trace and some hooks
  lib/common/logger/logger.ts
Labels: bug, cla: yes

#4605 chore: set version to 6.0.0
  npm-shrinkwrap.json
  package.json
Labels: new PR

#4609 style: misleading warning message
  lib/services/plugins-service.ts
  test/plugins-service.ts
Labels: cla: yes, new PR

#4610 fix: make logger backwards compatible
  lib/common/definitions/logger.d.ts
  lib/common/logger/logger.ts
  lib/common/test/unit-tests/stubs.ts
  lib/declarations.d.ts
  test/stubs.ts
Labels: bug, new PR

#4612 chore: merge release in master
  lib/common/definitions/logger.d.ts
  lib/common/logger/logger.ts
  lib/common/test/unit-tests/stubs.ts
  lib/declarations.d.ts
  test/stubs.ts
Labels: cla: yes, new PR

#4613 chore: update nativescript-dev-xcode to 0.2.0
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4615 fix: set correct link for legacy workflow warning
  lib/services/workflow-service.ts
Labels: cla: yes, new PR

#4614 fix: plugin create command needs more args for plugin seed
  docs/man_pages/lib-management/plugin-create.md
  lib/commands/plugin/create-plugin.ts
  lib/declarations.d.ts
  lib/options.ts
  test/plugin-create.ts
  test/stubs.ts
Labels: bug, cla: yes, new PR, plugins, severity: critical

#4621 docs: update changelog for 5.4.0 release
  CHANGELOG.md
Labels: cla: yes, new PR

#4622 chore: merge release-patch in release
  lib/services/plugins-service.ts
  npm-shrinkwrap.json
  package.json
  test/plugins-service.ts
Labels: cla: yes, new PR

#4625 chore: merge release in master
  CHANGELOG.md
  docs/man_pages/lib-management/plugin-create.md
  lib/commands/plugin/create-plugin.ts
  lib/declarations.d.ts
  lib/options.ts
  lib/services/plugins-service.ts
  lib/services/workflow-service.ts
  npm-shrinkwrap.json
  package.json
  test/plugin-create.ts
  test/plugins-service.ts
  test/stubs.ts
Labels: cla: yes, new PR

#4634 fix: set bundle option to webpack
  lib/options.ts
Labels: cla: yes

#4632 fix: generated App Store icon has alpha channel
  lib/definitions/project.d.ts
  lib/services/assets-generation/assets-generation-service.ts
  lib/services/project-data-service.ts
  resources/assets/image-definitions.json
Labels: cla: yes

#4652 feat: add vue drawer navigation template to create project command
  docs/man_pages/project/creation/create.md
  lib/commands/create-project.ts
  test/project-commands.ts
Labels: cla: yes

#4659 fix: pass --env.verbose to webpack compiler
  lib/common/definitions/logger.d.ts
  lib/common/logger/logger.ts
  lib/common/test/unit-tests/stubs.ts
  lib/services/webpack/webpack-compiler-service.ts
  test/stubs.ts
Labels: cla: yes

#4657 fix: respect App_Resources directly from project
  lib/services/android-project-service.ts
  lib/services/ios-project-service.ts
  lib/services/platform/prepare-native-platform-service.ts
  lib/services/webpack/webpack.d.ts
  test/stubs.ts
Labels: cla: yes

#4655 feat: expose methods to public API
  lib/bootstrap.ts
  lib/commands/debug.ts
  lib/commands/preview.ts
  lib/commands/run.ts
  lib/commands/test.ts
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/mobile-core/devices-service.ts
  lib/controllers/debug-controller.ts
  lib/controllers/deploy-controller.ts
  lib/controllers/preview-app-controller.ts
  lib/controllers/run-controller.ts
  lib/data/run-data.ts
  lib/definitions/debug.d.ts
  lib/definitions/livesync.d.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/definitions/project.d.ts
  lib/definitions/run.d.ts
  lib/emitters/preview-app-emitter.ts
  lib/emitters/run-emitter.ts
  lib/helpers/deploy-command-helper.ts
  lib/helpers/livesync-command-helper.ts
  lib/services/debug-data-service.ts
  lib/services/debug-service.ts
  lib/services/livesync-process-data-service.ts
  lib/services/livesync/android-device-livesync-service-base.ts
  lib/services/livesync/device-livesync-service-base.ts
  lib/services/livesync/ios-livesync-service.ts
  lib/services/livesync/platform-livesync-service-base.ts
  lib/services/livesync/playground/preview-app-livesync-service.ts
  lib/services/platform-environment-requirements.ts
  lib/services/test-execution-service.ts
  lib/services/webpack/webpack-compiler-service.ts
  lib/services/webpack/webpack.d.ts
  test/controllers/debug-controller.ts
  test/controllers/run-controller.ts
  test/nativescript-cli-lib.ts
  test/services/playground/preview-app-livesync-service.ts
  test/stubs.ts
Labels: cla: yes

#4662 fix: fix `InstallationLookupFailed` error is thrown when deploying on iOS device
  lib/controllers/run-controller.ts
  lib/services/build-info-file-service.ts
Labels: cla: yes

#4661 fix: prepare the project only once per run
  lib/helpers/livesync-command-helper.ts
Labels: cla: yes

#4660 feat: set webpack in production mode based on `--release` option
  lib/controllers/prepare-controller.ts
  lib/services/webpack/webpack-compiler-service.ts
  lib/services/webpack/webpack.d.ts
Labels: cla: yes
