Repository NativeScript/nativescript-cli, pull requests merged in 2019-01, with the labels that each got.

#4271 fix: do not show error from preview initialization when stop is called
  lib/commands/preview.ts
  lib/definitions/livesync.d.ts
  lib/services/livesync/livesync-service.ts
  lib/services/livesync/playground/preview-app-livesync-service.ts
  test/stubs.ts
Labels: bug

#4275 fix: splashscreen generation
  resources/assets/image-definitions.json
Labels: bug

#4286 fix: errors during debug on iOS
  lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
  lib/device-sockets/ios/packet-stream.ts
  npm-shrinkwrap.json
  package.json
Labels: bug, os: ios

#4288 fix: trying to stop app on simulator may kill CLI
  npm-shrinkwrap.json
  package.json
Labels: bug

#4294 fix: error may be raised during restart of app on ios Sim
  npm-shrinkwrap.json
  package.json
Labels: bug

#4282 Native source code and a Podfile without a plugin
  lib/constants.ts
  lib/definitions/project.d.ts
  lib/project-data.ts
  lib/services/cocoapods-service.ts
  lib/services/ios-project-service.ts
  lib/services/prepare-platform-native-service.ts
  test/cocoapods-service.ts
  test/ios-project-service.ts
  test/stubs.ts
Labels: feature

#4310 fix(build-ios): Use BUILD_DIR instead of CONFIGURATION_BUILD_DIR
  lib/definitions/platform.d.ts
  lib/services/android-project-service.ts
  lib/services/ios-project-service.ts
  lib/services/platform-service.ts
  test/ios-project-service.ts
  test/platform-commands.ts
  test/platform-service.ts
  test/services/android-project-service.ts
  test/stubs.ts
Labels: bug

#4321 fix: incorrect paths to CLI resources and files break commands
  lib/common/services/micro-templating-service.ts
  lib/config.ts
Labels: bug

#4317 feat: skip postinstall steps in case CLI is not installed globally
  lib/commands/post-install.ts
  lib/common/commands/post-install.ts
  lib/common/commands/preuninstall.ts
  lib/common/definitions/config.d.ts
  lib/common/helpers.ts
  lib/common/test/unit-tests/helpers.ts
  lib/config.ts
  postinstall.js
  test/commands/post-install.ts
  test/post-install.ts
Labels: feature

#4322 fix: high cpu usage during livesync
  lib/common/mobile/mobile-core/devices-service.ts
  lib/common/test/unit-tests/mobile/devices-service.ts
Labels: bug

#4299 chore: remove installPods property from platform's project interface
  lib/bootstrap.ts
  lib/declarations.d.ts
  lib/definitions/project.d.ts
  lib/services/android-project-service.ts
  lib/services/cocoapods-service.ts
  lib/services/ios-project-service.ts
  lib/services/prepare-platform-native-service.ts
  lib/services/xcconfig-service.ts
  lib/services/xcproj-service.ts
  lib/tools/node-modules/node-modules-dest-copy.ts
  test/cocoapods-service.ts
  test/ios-project-service.ts
  test/npm-support.ts
  test/platform-service.ts
  test/plugin-prepare.ts
  test/stubs.ts
  test/xcconfig-service.ts
Labels: technical debt

#4328 fix: prompt to install Xcode Command Line Tools when listing devices
  npm-shrinkwrap.json
  package.json
Labels: bug
