Repository NativeScript/nativescript-cli, pull requests merged in 2019-12, with the labels that each got.

#5166 fix: prepare of pods should work on case-sensitive systems
  lib/controllers/preview-app-controller.ts
  lib/definitions/plugins.d.ts
  lib/services/plugins-service.ts
  test/ios-project-service.ts
  test/plugins-service.ts
  test/services/playground/preview-app-livesync-service.ts
Labels: cla: yes

#5171 chore: improve log trace messages
  lib/common/dispatchers.ts
  lib/nativescript-cli.ts
  lib/services/project-changes-service.ts
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#5176 docs: remove outdated README content
  README.md
Labels: cla: yes

#5179 docs: update outdate parts of contributing.md
  CONTRIBUTING.md
Labels: cla: yes

#5163 fix: sync all files when a HMR update is not possible in order to avoid multiple HMR syncs after restart
  Gruntfile.js
  docs/man_pages/project/testing/test-init.md
  lib/common/services/micro-templating-service.ts
  lib/controllers/preview-app-controller.ts
  lib/controllers/run-controller.ts
  lib/options.ts
  lib/services/livesync/android-livesync-service.ts
  lib/services/livesync/ios-device-livesync-service.ts
  lib/services/webpack/webpack-compiler-service.ts
  npm-shrinkwrap.json
  package.json
  yarn.lock
Labels: cla: yes

#5178 feat: doctor improvements
  lib/common/commands/doctor.ts
  lib/common/declarations.d.ts
  lib/definitions/platform.d.ts
  lib/services/doctor-service.ts
  lib/services/platform-environment-requirements.ts
  test/services/doctor-service.ts
Labels: cla: yes

#5182 feat: support API 29 emulators during available devices detection
  lib/common/mobile/android/android-emulator-services.ts
  lib/common/mobile/emulator-helper.ts
Labels: cla: yes

#5184 chore: marge release into master
  lib/common/mobile/android/android-emulator-services.ts
  lib/common/mobile/emulator-helper.ts
Labels: cla: yes

#5172 feat: Support iOS Runtime for Catalyst
  lib/services/ios-project-service.ts
Labels: cla: yes, feature

#5185 chore: 6.3.0 changelog
  CHANGELOG.md
Labels: cla: yes

#5188 fix: Add warning for missing modulemap in `src`
  lib/services/ios-project-service.ts
Labels: cla: yes, needs better error msg, os: ios, prepare
