Repository NativeScript/nativescript-cli, pull requests merged in 2019-04, with the labels that each got.

#4484 chore: update TypeScript dev dependencies
  lib/common/child-process.ts
  lib/common/definitions/cli-global.d.ts
  lib/common/definitions/lodash.d.ts
  lib/common/file-system.ts
  lib/common/helpers.ts
  lib/common/host-info.ts
  lib/common/http-client.ts
  lib/common/mobile/android/android-application-manager.ts
  lib/common/mobile/ios/device/ios-device-operations.ts
  lib/common/mobile/mobile-core/android-device-discovery.ts
  lib/common/mobile/mobile-core/android-emulator-discovery.ts
  lib/common/mobile/mobile-core/devices-service.ts
  lib/common/mobile/mobile-core/ios-simulator-discovery.ts
  lib/common/prompter.ts
  lib/common/services/message-contract-generator.ts
  lib/common/services/messages-service.ts
  lib/common/services/net-service.ts
  lib/common/test/unit-tests/android-log-filter.ts
  lib/common/test/unit-tests/ios-log-filter.ts
  lib/common/test/unit-tests/mobile/android/logcat-helper.ts
  lib/common/test/unit-tests/mobile/devices-service.ts
  lib/common/test/unit-tests/yok.ts
  lib/helpers/livesync-command-helper.ts
  lib/node-package-manager.ts
  lib/services/android-plugin-build-service.ts
  lib/services/app-files-updater.ts
  lib/services/debug-service.ts
  lib/services/init-service.ts
  lib/services/ios-project-service.ts
  lib/services/livesync/livesync-service.ts
  lib/services/livesync/platform-livesync-service-base.ts
  lib/services/livesync/playground/devices/preview-devices-service.ts
  lib/services/pacote-service.ts
  lib/services/platform-service.ts
  lib/services/prepare-platform-service.ts
  lib/services/project-changes-service.ts
  lib/services/project-service.ts
  lib/services/subscription-service.ts
  lib/yarn-package-manager.ts
  npm-shrinkwrap.json
  package.json
  test/cocoapods-service.ts
  test/debug.ts
  test/ios-entitlements-service.ts
  test/ios-project-service.ts
  test/platform-service.ts
  test/plugins-service.ts
  test/project-templates-service.ts
  test/services/debug-service.ts
  test/services/ios-debugger-port-service.ts
  test/services/subscription-service.ts
  test/stubs.ts
  test/update.ts
  tslint.json
Labels: cla: yes, new PR

#4490 chore update the package locks
  npm-shrinkwrap.json
  yarn.lock
Labels: cla: yes, new PR

#4491 Merge release into master
  npm-shrinkwrap.json
  yarn.lock
Labels: cla: yes, new PR

#4489 chore: update log4js to its latest version
  config/config.json
  lib/android-tools-info.ts
  lib/common/commands/device/list-devices.ts
  lib/common/definitions/config.d.ts
  lib/common/definitions/log4js.d.ts
  lib/common/definitions/logger.d.ts
  lib/common/logger.ts
  lib/common/test/unit-tests/stubs.ts
  lib/config.ts
  npm-shrinkwrap.json
  package.json
  test/stubs.ts
  yarn.lock
Labels: cla: yes, new PR

#4493 fix: errors are shown on postinstall when using sudo
  lib/commands/post-install.ts
  test/commands/post-install.ts
Labels: bug, cla: yes, new PR

#4494 fix: detect java correctly
  npm-shrinkwrap.json
  package.json
  yarn.lock
Labels: bug, cla: yes, new PR

#4492 feat(kinvey): provide correct data to preview-sdk based on the schema
  lib/bootstrap.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/services/livesync/playground/preview-app-constants.ts
  lib/services/livesync/playground/preview-app-livesync-service.ts
  lib/services/livesync/playground/preview-qr-code-service.ts
  lib/services/livesync/playground/preview-schema-service.ts
  lib/services/livesync/playground/preview-sdk-service.ts
  npm-shrinkwrap.json
  package.json
  test/services/playground/preview-app-livesync-service.ts
  test/services/playground/preview-schema-service.ts
  test/services/preview-sdk-service.ts
  yarn.lock
Labels: cla: yes, new PR

#4496 fix: change ksplay to kspreview schema
  lib/services/livesync/playground/preview-qr-code-service.ts
  lib/services/livesync/playground/preview-schema-service.ts
  test/services/playground/preview-schema-service.ts
  test/services/preview-sdk-service.ts
Labels: cla: yes, new PR

#4498 fix(kinvey): use correct store ids for preview and scanner apps
  lib/services/livesync/playground/preview-schema-service.ts
  package.json
  test/services/playground/preview-schema-service.ts
Labels: cla: yes, new PR

#4502 chore: merge release into master
  lib/bootstrap.ts
  lib/commands/post-install.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/services/livesync/playground/preview-app-constants.ts
  lib/services/livesync/playground/preview-app-livesync-service.ts
  lib/services/livesync/playground/preview-qr-code-service.ts
  lib/services/livesync/playground/preview-schema-service.ts
  lib/services/livesync/playground/preview-sdk-service.ts
  npm-shrinkwrap.json
  package.json
  test/commands/post-install.ts
  test/services/playground/preview-app-livesync-service.ts
  test/services/playground/preview-schema-service.ts
  test/services/preview-sdk-service.ts
  yarn.lock
Labels: new PR

#4501 fix(grunt): generate unit testing dependencies on grunt rebuild command
  Gruntfile.js
Labels: cla: yes, new PR, no-changelog

#4505 fix: remove legacy code related to old structure of android project
  lib/services/android-project-service.ts
Labels: cla: yes, new PR

#4510 fix: handle HTTP 304 response status code
  lib/common/constants.ts
  lib/common/http-client.ts
Labels: bug, cla: yes, new PR

#4516 chore: remove the code related to js prepare as webpack overrides prepareJS method with own logic
  lib/definitions/platform.d.ts
  lib/definitions/plugins.d.ts
  lib/services/plugins-service.ts
  lib/services/prepare-platform-js-service.ts
  lib/tools/node-modules/node-modules-builder.ts
  lib/tools/node-modules/node-modules-dest-copy.ts
  test/platform-service.ts
  test/plugin-prepare.ts
  test/plugins-service.ts
Labels: cla: yes, new PR

#4517 chore: remove projectTemplate logic
  lib/commands/add-platform.ts
  lib/commands/appstore-upload.ts
  lib/commands/build.ts
  lib/commands/clean-app.ts
  lib/commands/install.ts
  lib/commands/platform-clean.ts
  lib/commands/prepare.ts
  lib/commands/update-platform.ts
  lib/commands/update.ts
  lib/declarations.d.ts
  lib/definitions/platform.d.ts
  lib/definitions/project.d.ts
  lib/helpers/deploy-command-helper.ts
  lib/options.ts
  lib/services/livesync/livesync-service.ts
  lib/services/local-build-service.ts
  lib/services/platform-service.ts
  lib/services/prepare-platform-js-service.ts
  test/platform-service.ts
Labels: cla: yes, new PR

#4520 chore: remove the legacy code from android-project-service
  lib/common/helpers.ts
  lib/definitions/project.d.ts
  lib/services/android-project-service.ts
  lib/services/ios-project-service.ts
  lib/services/platform-service.ts
  test/debug.ts
  test/stubs.ts
Labels: cla: yes, new PR

#4521 chore: delete plugin variables service
  lib/common/declarations.d.ts
  lib/common/plugin-variables-helper.ts
  lib/definitions/plugins.d.ts
  lib/services/ios-project-service.ts
  lib/services/plugin-variables-service.ts
  lib/services/plugins-service.ts
  test/ios-project-service.ts
  test/plugin-variables-service.ts
  test/update.ts
Labels: cla: yes, new PR

#4519 docs: add environment flags in CLI help
  docs/build-jekyll-md.sh
  docs/man_pages/project/testing/build-android.md
  docs/man_pages/project/testing/build-ios.md
  docs/man_pages/project/testing/build.md
  docs/man_pages/project/testing/run-android.md
  docs/man_pages/project/testing/run-ios.md
  docs/man_pages/project/testing/run.md
Labels: cla: yes, new PR

#4526 feat: add iCloudContainerEnvironment build option
  docs/man_pages/project/testing/build-ios.md
  lib/commands/appstore-upload.ts
  lib/commands/build.ts
  lib/declarations.d.ts
  lib/definitions/project.d.ts
  lib/helpers/livesync-command-helper.ts
  lib/options.ts
  lib/services/ios-project-service.ts
  lib/services/livesync/livesync-service.ts
  lib/services/platform-service.ts
  lib/services/test-execution-service.ts
  test/services/android-project-service.ts
Labels: cla: yes, new PR

#4482 feat: add sample test in TypeScript for ts projects on test init command
  config/test-dependencies.json
  lib/commands/test-init.ts
  lib/common/declarations.d.ts
  resources/test/example.jasmine.ts
  resources/test/example.mocha.ts
  resources/test/example.qunit.ts
  resources/test/karma.conf.js
  tsconfig.json
Labels: cla: yes, new PR

#4531 fix: support custom tagged android runtime versions
  lib/services/android-project-service.ts
Labels: cla: yes, new PR

#4529 chore: remove legacy code from ios-project-service
  lib/definitions/plugins.d.ts
  lib/definitions/project.d.ts
  lib/services/android-project-service.ts
  lib/services/ios-project-service.ts
  lib/services/plugins-service.ts
  lib/services/prepare-platform-native-service.ts
  test/stubs.ts
Labels: new PR

#4532 chore: merge release into master
  Gruntfile.js
  config/test-dependencies.json
  lib/commands/test-init.ts
  lib/common/constants.ts
  lib/common/declarations.d.ts
  lib/common/http-client.ts
  lib/services/android-project-service.ts
  resources/test/example.jasmine.ts
  resources/test/example.mocha.ts
  resources/test/example.qunit.ts
  resources/test/karma.conf.js
  tsconfig.json
Labels: cla: yes, new PR

#4536 chore: add changelog for 5.3.2 release
  CHANGELOG.md
Labels: cla: yes, new PR

#4538 Shows an appropriate message while trying to run the app in a non-project folder
  lib/commands/run.ts
Labels: cla: yes, new PR

#4537 refactor: refactor the logic for building android projects
  lib/bootstrap.ts
  lib/definitions/gradle.d.ts
  lib/definitions/project.d.ts
  lib/services/android-project-service.ts
  lib/services/android/gradle-build-args-service.ts
  lib/services/android/gradle-build-service.ts
  lib/services/android/gradle-command-service.ts
  lib/services/platform-service.ts
  test/plugins-service.ts
  test/services/android-project-service.ts
  test/services/android/gradle-build-args-service.ts
Labels: cla: yes, new PR

#4547 fix: fix upload to appstore for accounts without 2 factor authentication
  lib/bootstrap.ts
  lib/commands/appstore-list.ts
  lib/commands/appstore-upload.ts
  lib/declarations.d.ts
  lib/services/apple-portal/apple-portal-application-service.ts
  lib/services/apple-portal/apple-portal-cookie-service.ts
  lib/services/apple-portal/apple-portal-session-service.ts
  lib/services/apple-portal/definitions.d.ts
  lib/services/itmstransporter-service.ts
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4549 chore: automate publish of webpack tag
  .travis.yml
  .travis/add-publishConfig.js
Labels: cla: yes, new PR

#4555 fix: fix the unit tests execution with istanbul
  lib/services/android/gradle-command-service.ts
  test/services/android/gradle-build-args-service.ts
Labels: cla: yes, new PR

#4554 refactor: refactor ios build
  lib/bootstrap.ts
  lib/commands/appstore-upload.ts
  lib/constants.ts
  lib/declarations.d.ts
  lib/definitions/project.d.ts
  lib/definitions/xcode.d.ts
  lib/services/android-project-service.ts
  lib/services/ios-project-service.ts
  lib/services/ios/export-options-plist-service.ts
  lib/services/ios/ios-signing-service.ts
  lib/services/ios/xcodebuild-args-service.ts
  lib/services/ios/xcodebuild-command-service.ts
  lib/services/ios/xcodebuild-service.ts
  lib/services/platform-service.ts
  lib/services/xcproj-service.ts
  test/ios-project-service.ts
  test/services/ios/export-options-plist-service.ts
  test/services/ios/ios-signing-service.ts
  test/services/ios/xcodebuild-args-service.ts
  test/services/ios/xcodebuild-service.ts
  test/tns-appstore-upload.ts
Labels: cla: yes, new PR

#4559 fix: prepare xcconfig files for all conigurations
  lib/declarations.d.ts
  lib/services/cocoapods-service.ts
  lib/services/ios-project-service.ts
  lib/services/xcconfig-service.ts
  npm-shrinkwrap.json
  package.json
  test/ios-project-service.ts
Labels: bug, cla: yes, new PR

#4557 chore: merge release into master
  CHANGELOG.md
  lib/bootstrap.ts
  lib/commands/appstore-list.ts
  lib/commands/appstore-upload.ts
  lib/declarations.d.ts
  lib/services/apple-portal/apple-portal-application-service.ts
  lib/services/apple-portal/apple-portal-cookie-service.ts
  lib/services/apple-portal/apple-portal-session-service.ts
  lib/services/apple-portal/definitions.d.ts
  lib/services/itmstransporter-service.ts
Labels: cla: yes, new PR

#4546 feat: deprecate the legacy workflow and recommend the new one
  lib/bootstrap.ts
  lib/commands/build.ts
  lib/commands/debug.ts
  lib/commands/deploy.ts
  lib/commands/prepare.ts
  lib/commands/preview.ts
  lib/commands/run.ts
  lib/commands/test.ts
  lib/commands/update.ts
  lib/common/helpers.ts
  lib/declarations.d.ts
  lib/definitions/platform.d.ts
  lib/definitions/project.d.ts
  lib/helpers/bundle-validator-helper.ts
  lib/helpers/livesync-command-helper.ts
  lib/options.ts
  lib/project-data.ts
  lib/services/livesync/playground/preview-app-livesync-service.ts
  lib/services/platform-service.ts
  lib/services/project-data-service.ts
  lib/services/workflow-service.ts
  test/debug.ts
  test/helpers/bundle-validator-helper.ts
  test/package-installation-manager.ts
  test/platform-commands.ts
  test/platform-service.ts
  test/services/playground/preview-app-livesync-service.ts
  test/services/project-data-service.ts
  test/stubs.ts
  test/update.ts
Labels: cla: yes, new PR

#4566 fix: fix the workflow warnings on Windows
  lib/common/helpers.ts
Labels: new PR

#4564 chore: add changelog for 5.3.3 and 5.3.4
  CHANGELOG.md
Labels: cla: yes, new PR

#4572 chore: add changelog for 5.3.1 release
  CHANGELOG.md
Labels: cla: yes, new PR

#4565 fix: use proxy only for remote requests
  lib/common/http-client.ts
Labels: cla: yes, new PR
