Repository NativeScript/nativescript-cli, pull requests merged in 2019-03, with the labels that each got.

#4412 fix: avoid leaked lock files for more than 10 seconds
  Gruntfile.js
  lib/common/Gruntfile.js
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/services/livesync-service-base.ts
  lib/common/services/lock-service.ts
  lib/common/test/unit-tests/stubs.ts
  lib/common/tsconfig.json
  lib/common/tslint.json
  lib/definitions/lock-service.d.ts
  lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4413 chore: update the yarn.lock
  yarn.lock
Labels: cla: yes, new PR

#4414 chore: merge 'release' into 'master'
  Gruntfile.js
  docs/man_pages/project/testing/build-android.md
  docs/man_pages/project/testing/build-ios.md
  lib/bootstrap.ts
  lib/commands/test.ts
  lib/common/Gruntfile.js
  lib/common/declarations.d.ts
  lib/common/definitions/mobile.d.ts
  lib/common/errors.ts
  lib/common/helpers.ts
  lib/common/mobile/ios/device/ios-application-manager.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
  lib/common/services/livesync-service-base.ts
  lib/common/services/lock-service.ts
  lib/common/test/unit-tests/helpers.ts
  lib/common/test/unit-tests/stubs.ts
  lib/common/tsconfig.json
  lib/common/tslint.json
  lib/constants.ts
  lib/definitions/lock-service.d.ts
  lib/definitions/project.d.ts
  lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
  lib/project-data.ts
  lib/services/cocoapods-platform-manager.ts
  lib/services/cocoapods-service.ts
  lib/services/doctor-service.ts
  lib/services/ios-debugger-port-service.ts
  lib/services/ios-project-service.ts
  lib/services/livesync/ios-device-livesync-service.ts
  lib/services/platform-service.ts
  lib/services/project-data-service.ts
  lib/services/test-execution-service.ts
  npm-shrinkwrap.json
  package.json
  resources/test/plugin-with-scoped-dependency.zip
  test/cocoapods-service.ts
  test/ios-project-service.ts
  test/npm-support.ts
  test/platform-commands.ts
  test/platform-service.ts
  test/project-service.ts
  test/services/doctor-service.ts
  test/services/ios-debugger-port-service.ts
  test/services/platform-environment-requirements.ts
  test/services/project-data-service.ts
  test/services/test-execution-serice.ts
  test/stubs.ts
  test/tools/node-modules/node-modules-dependencies-builder.ts
  yarn.lock
Labels: cla: yes, new PR

#4418 feat: keep the unit testing dependencies up-to-date and stable
  .gitignore
  Gruntfile.js
  config/test-dependencies.json
  lib/bootstrap.ts
  lib/commands/test-init.ts
  lib/definitions/project.d.ts
  lib/services/test-initialization-service.ts
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4421 Tachev/merge release into master
  .gitignore
  CHANGELOG.md
  Gruntfile.js
  config/test-dependencies.json
  lib/bootstrap.ts
  lib/commands/test-init.ts
  lib/definitions/project.d.ts
  lib/services/test-initialization-service.ts
  npm-shrinkwrap.json
  package.json
Labels: new PR

#4427 chore: set version to 5.2.3
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4426 fix: retry stuck requests
  lib/common/http-client.ts
Labels: bug, cla: yes

#4428 chore: update Changelog for 5.2.2 and 5.2.3 releases
  CHANGELOG.md
Labels: cla: yes, new PR

#4430 chore: merge release in master
  CHANGELOG.md
  lib/common/http-client.ts
Labels: cla: yes

#4411 feat: enable hmr by default for new projects
  lib/common/services/commands-service.ts
  lib/declarations.d.ts
  lib/definitions/project.d.ts
  lib/options.ts
  lib/project-data.ts
  test/options.ts
  test/stubs.ts
Labels: cla: yes, new PR

#4434 fix: warnings for short imports should be shown correctly
  lib/services/doctor-service.ts
  lib/services/project-data-service.ts
  package.json
  test/services/doctor-service.ts
Labels: bug, cla: yes, new PR

#4442 fix: get Xcode version correctly
  lib/services/ios-project-service.ts
  test/ios-project-service.ts
Labels: bug, cla: yes, new PR

#4419 fix: remove the logic for skipCopyTnsModules and skipCopyAppResourcesFiles
  lib/definitions/platform.d.ts
  lib/services/platform-service.ts
  lib/services/prepare-platform-js-service.ts
Labels: cla: yes, new PR, technical debt

#4444 fix: don't change the options in httpRequestCore
  lib/common/http-client.ts
Labels: bug, new PR

#4445 chore: merge release into master
  lib/common/http-client.ts
  lib/services/doctor-service.ts
  lib/services/project-data-service.ts
  test/services/doctor-service.ts
Labels: new PR

#4415 I tried my best to make your readme a little better. I think it looks nice : )
  README.md
Labels: cla: yes, new PR

#4437 feat: implement unit testing with bundle
  config/test-dependencies.json
  lib/commands/test-init.ts
  lib/common/declarations.d.ts
  lib/definitions/project.d.ts
  lib/services/test-execution-service.ts
  lib/services/test-initialization-service.ts
  resources/test/karma.conf.js
Labels: cla: yes, new PR

#4447 fix: change nativescript image in readme.md
  README.md
Labels: new PR

#4449 chore: update xcode dependencies
  lib/definitions/xcode.d.ts
  lib/node/xcode.ts
  npm-shrinkwrap.json
  package.json
  test/ios-project-service.ts
Labels: cla: yes, new PR

#4452 fix: fix the "cannot read property imageIdentifier of undefined" error
  lib/common/mobile/android/android-emulator-services.ts
Labels: cla: yes, new PR

#4454 fix: warnings for short imports should not be shown for minified code
  lib/services/doctor-service.ts
  test/services/doctor-service.ts
Labels: bug, cla: yes, new PR

#4453 Kddimitrov/ios app extensions
  lib/bootstrap.ts
  lib/constants.ts
  lib/definitions/project.d.ts
  lib/definitions/xcode.d.ts
  lib/node/xcode.ts
  lib/services/ios-extensions-service.ts
  lib/services/ios-project-service.ts
  test/ios-project-service.ts
Labels: cla: yes, new PR

#4457 fix: remove the HMR Beta warnings as all critical issue are fixed
  lib/services/livesync/livesync-service.ts
Labels: new PR

#4459 fix: raise debuggerAttached only if app is restarted
  lib/definitions/livesync.d.ts
  lib/services/livesync/livesync-service.ts
Labels: cla: yes, new PR

#4455 fix: do not wait 60 seconds for debugger port when the app is crashed
  lib/common/constants.ts
  lib/common/mobile/ios/device/ios-device.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/mobile/ios/simulator/ios-simulator-device.ts
  lib/definitions/hmr-status-service.d.ts
  lib/definitions/ios-debugger-port-service.d.ts
  lib/services/hmr-status-service.ts
  lib/services/ios-debugger-port-service.ts
  lib/services/livesync/livesync-service.ts
  test/services/ios-debugger-port-service.ts
Labels: cla: yes, new PR

#4438 chore: add e2e test info in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes, new PR

#4460 chore: update nativescript-dev-xcode lib
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4461 fix: start iOS simulator logs before starting the app
  lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
Labels: cla: yes, new PR

#4462 chore: set version to 5.4.0
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4464 feat: add ability to pass schema to preview app from nsconfig file
  lib/commands/preview.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/definitions/project.d.ts
  lib/project-data.ts
  lib/services/livesync/livesync-service.ts
  lib/services/livesync/playground/preview-sdk-service.ts
  lib/services/platform-environment-requirements.ts
  test/services/preview-sdk-service.ts
  test/stubs.ts
Labels: cla: yes, new PR

#4465 fix: debugging clients are now able to debug with debug-brk
  lib/commands/debug.ts
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/services/livesync/ios-device-livesync-service.ts
Labels: cla: yes, new PR

#4470 fix: add support for android 'Q'
  lib/common/mobile/android/android-device.ts
Labels: cla: yes, new PR

#4473 chore: add wanrning for extensions beta support
  lib/definitions/project.d.ts
  lib/services/ios-extensions-service.ts
  lib/services/ios-project-service.ts
Labels: cla: yes, new PR

#4471 fix: update ns-dev-xcode to fix extension framework removal
  npm-shrinkwrap.json
  package.json
Labels: cla: yes, new PR

#4476 chore: update Changelog for 5.3.0
  CHANGELOG.md
Labels: new PR

#4479 chore: merge release-patch in release
  lib/commands/preview.ts
  lib/common/declarations.d.ts
  lib/common/mobile/android/android-device.ts
  lib/constants.ts
  lib/definitions/livesync.d.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/definitions/project.d.ts
  lib/helpers/livesync-command-helper.ts
  lib/project-data.ts
  lib/services/livesync/livesync-service.ts
  lib/services/livesync/playground/preview-sdk-service.ts
  lib/services/platform-environment-requirements.ts
  npm-shrinkwrap.json
  package.json
  test/services/preview-sdk-service.ts
  test/stubs.ts
Labels: cla: yes, new PR

#4481 chore: merge release into master
  CHANGELOG.md
  lib/commands/debug.ts
  lib/commands/preview.ts
  lib/common/declarations.d.ts
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/android/android-device.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/constants.ts
  lib/definitions/livesync.d.ts
  lib/definitions/preview-app-livesync.d.ts
  lib/definitions/project.d.ts
  lib/helpers/livesync-command-helper.ts
  lib/project-data.ts
  lib/services/ios-extensions-service.ts
  lib/services/ios-project-service.ts
  lib/services/livesync/ios-device-livesync-service.ts
  lib/services/livesync/livesync-service.ts
  lib/services/livesync/playground/preview-sdk-service.ts
  lib/services/platform-environment-requirements.ts
  npm-shrinkwrap.json
  package.json
  test/services/preview-sdk-service.ts
  test/stubs.ts
Labels: cla: yes, new PR

#4483 Device/emulator detection fixes
  PublicAPI.md
  lib/common/bootstrap.ts
  lib/common/declarations.d.ts
  lib/common/definitions/mobile.d.ts
  lib/common/definitions/timers.d.ts
  lib/common/mobile/android/android-virtual-device-service.ts
  lib/common/mobile/mobile-core/devices-service.ts
  lib/common/test/unit-tests/mobile/android-virtual-device-service.ts
  lib/common/test/unit-tests/mobile/devices-service.ts
  lib/common/timers.ts
  lib/sys-info.ts
  npm-shrinkwrap.json
  package.json
  test/ios-project-service.ts
  test/nativescript-cli-lib.ts
Labels: bug, cla: yes, new PR
