Repository NativeScript/nativescript-cli, pull requests merged in 2019-06, with the labels that each got.

#4664 fix: cloud run command does not respect useLegacyWorkflow flag
  lib/common/services/commands-service.ts
  lib/declarations.d.ts
  lib/options.ts
  test/options.ts
Labels: bug, cla: yes

#4663 fix: fix the application crash on device on deploy command
  lib/commands/build.ts
  lib/commands/deploy.ts
  lib/commands/prepare.ts
  lib/controllers/deploy-controller.ts
Labels: cla: yes

#4670 fix: pass correct args when using deprecated logger API
  lib/common/logger/logger.ts
Labels: bug, cla: yes

#4666 fix: incorrect error for non-supported Node.js version
  lib/common/verify-node-version.ts
Labels: bug

#4672 fix: fix cloud run command
  lib/controllers/run-controller.ts
  lib/helpers/livesync-command-helper.ts
Labels: cla: yes

#4675 feat: update supported Node.js versions
  lib/common/verify-node-version.ts
  package.json
Labels: cla: yes, feature

#4678 fix: fix run with --justlaunch
  lib/controllers/prepare-controller.ts
Labels: cla: yes

#4677 fix: fix release run for android
  lib/controllers/build-controller.ts
  lib/controllers/deploy-controller.ts
  lib/definitions/gradle.d.ts
  lib/definitions/run.d.ts
  lib/helpers/deploy-command-helper.ts
  lib/helpers/livesync-command-helper.ts
  lib/services/android-project-service.ts
  lib/services/android/gradle-build-args-service.ts
  lib/services/android/gradle-build-service.ts
  lib/services/platform/prepare-native-platform-service.ts
  lib/services/webpack/webpack.d.ts
  test/services/android/gradle-build-args-service.ts
  test/stubs.ts
Labels: cla: yes

#4682 fix: fix tns preview
  lib/controllers/preview-app-controller.ts
Labels: cla: yes

#4680 feat: remove init command
  docs/man_pages/project/creation/init.md
  lib/bootstrap.ts
  lib/commands/init.ts
  lib/declarations.d.ts
  lib/services/project-init-service.ts
Labels: cla: yes

#4679 fix: logger fails to print null objects
  lib/common/logger/logger.ts
  lib/common/test/unit-tests/logger.ts
Labels: bug, cla: yes

#4683 fix: handle correctly runtime files
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4685 chore: merge release into master
  lib/common/logger/logger.ts
  lib/common/services/commands-service.ts
  lib/common/test/unit-tests/logger.ts
  lib/common/verify-node-version.ts
  lib/declarations.d.ts
  lib/definitions/project.d.ts
  lib/options.ts
  lib/services/assets-generation/assets-generation-service.ts
  lib/services/project-data-service.ts
  resources/assets/image-definitions.json
  test/options.ts
Labels: cla: yes

#4671 fix: don't check all node_modules from `checkForChanges` method
  lib/controllers/prepare-controller.ts
  lib/controllers/run-controller.ts
  lib/definitions/project-changes.d.ts
  lib/services/platform/prepare-native-platform-service.ts
  lib/services/project-changes-service.ts
  test/project-changes-service.ts
  test/stubs.ts
Labels: cla: yes

#4686 chore: merge master branch
  docs/man_pages/project/creation/create.md
  lib/commands/create-project.ts
  lib/common/logger/logger.ts
  lib/common/services/commands-service.ts
  lib/common/test/unit-tests/logger.ts
  lib/common/verify-node-version.ts
  lib/declarations.d.ts
  lib/definitions/project.d.ts
  lib/options.ts
  lib/services/assets-generation/assets-generation-service.ts
  lib/services/project-data-service.ts
  package.json
  resources/assets/image-definitions.json
  test/options.ts
  test/project-commands.ts
Labels: cla: yes

#4693 fix: unable to start iOS simulator when Android is not setup
  lib/common/mobile/mobile-core/devices-service.ts
Labels: bug, cla: yes, os: android, os: ios

#4690 fix: respect `--for-device` option when building for iOS device
  lib/data/build-data.ts
Labels: cla: yes

#4702 fix: show deprecation message on tns init
  lib/commands/init.ts
Labels: cla: yes

#4703 fix: enable source maps by default
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4689 fix: emit only `bundle.<hash>.hot-update.js` and `<hash>.hot-update.json` files when `--hmr` is provided
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4704 fix: disable the Webpack plugins which require the files from the file system
  resources/test/karma.conf.js
Labels: cla: yes, no-changelog

#4694 fix: debugging on iOS Device is very slow
  npm-shrinkwrap.json
  package.json
Labels: bug, cla: yes, os: ios

#4708 fix: fix cannot read property sourceMap of undefined
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4710 fix: add preview-sync and watchPatterns hooks
  lib/controllers/prepare-controller.ts
  lib/controllers/preview-app-controller.ts
  test/services/playground/preview-app-livesync-service.ts
Labels: cla: yes

#4712 fix: populate correctly prepareData and buildData when they are based on $options
  lib/helpers/livesync-command-helper.ts
Labels: cla: yes

#4709 fix: ensure dependencies are installed before spawning webpack
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4711 fix: fix plugin's development workflow
  lib/controllers/prepare-controller.ts
  lib/controllers/run-controller.ts
  test/controllers/prepare-controller.ts
Labels: cla: yes

#4714 chore: merge release into master
  lib/commands/init.ts
  lib/common/mobile/mobile-core/devices-service.ts
  npm-shrinkwrap.json
  package.json
  resources/test/karma.conf.js
Labels: cla: yes

#4716 fix: increase the max process's size in order to prevent "JavaScript heap out of memory error"
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4719 fix: save correct .nsprepareinfo file on cloud commands
  lib/controllers/prepare-controller.ts
  lib/services/platform/add-platform-service.ts
  lib/services/platform/prepare-native-platform-service.ts
  lib/services/project-changes-service.ts
  lib/services/webpack/webpack.d.ts
  test/project-changes-service.ts
  test/stubs.ts
Labels: cla: yes

#4722 Add time(hours, minutes and seconds) to cli version.
  .travis.yml
Labels: cla: yes

#4717 fix: extend process's max size only for `x64` processes
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4728 fix: fix deploy on iOS devices
  lib/controllers/deploy-controller.ts
Labels: cla: yes

#4725 fix: restore application when the broken xml file is fixed
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4723 fix: start webpack in non watch mode for release builds with snapshot
  lib/helpers/livesync-command-helper.ts
Labels: cla: yes

#4727 fix: build only once when there are more than one android devices
  lib/controllers/run-controller.ts
Labels: cla: yes

#4730 docs: update changelog for 5.4.1 release
  CHANGELOG.md
Labels: cla: yes

#4732 fix: hmr for iOS does not work on Windows
  lib/common/mobile/ios/device/ios-device.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/mobile/ios/simulator/ios-simulator-device.ts
  package.json
Labels: bug, cla: yes, os: ios, os: windows

#4734 fix: fix the workflow of preview-sync hook
  lib/controllers/preview-app-controller.ts
Labels: cla: yes

#4733 fix: fix `tns platform list` and `tns platform clean` commands
  lib/helpers/platform-command-helper.ts
Labels: cla: yes

#4735 feat: drop support for Xcode < 10
  npm-shrinkwrap.json
  package.json
Labels: build, os: ios

#4724 fix: fix the way android appResources are processed
  lib/services/android-project-service.ts
Labels: cla: yes

#4736 fix: show warning when --env.snapshot is provided for debug builds
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4740 fix: initialize nativeChanged with true when checking for changes
  lib/services/project-changes-service.ts
Labels: cla: yes

#4743 fix: fix `tns deploy ios --justlaunch` when there are connected device and simulator
  lib/controllers/deploy-controller.ts
Labels: cla: yes

#4738 fix: enable passing iOS codesigning options to LiveSync operations
  lib/controllers/debug-controller.ts
  lib/controllers/run-controller.ts
  lib/definitions/livesync.d.ts
  lib/definitions/prepare.d.ts
  lib/helpers/deploy-command-helper.ts
  lib/helpers/livesync-command-helper.ts
  test/controllers/run-controller.ts
Labels: bug, cla: yes, code signing, os: ios

#4745 docs: update Changelog for 5.4.2
  CHANGELOG.md
Labels: cla: yes

#4673 Kddimitrov/webpack source maps log
  .gitignore
  Gruntfile.js
  lib/bootstrap.ts
  lib/common/commands/device/run-application.ts
  lib/common/commands/device/stop-application.ts
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/android/android-application-manager.ts
  lib/common/mobile/device-log-emitter.ts
  lib/common/mobile/device-log-provider-base.ts
  lib/common/mobile/device-log-provider.ts
  lib/common/mobile/ios/device/ios-application-manager.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
  lib/common/mobile/mobile-core/devices-service.ts
  lib/common/test/unit-tests/android-application-manager.ts
  lib/common/test/unit-tests/android-log-filter.ts
  lib/common/test/unit-tests/appbuilder/device-log-provider.ts
  lib/common/test/unit-tests/ios-log-filter.ts
  lib/common/test/unit-tests/log-filter.ts
  lib/common/test/unit-tests/mobile/android-device-file-system.ts
  lib/common/test/unit-tests/mobile/application-manager-base.ts
  lib/common/test/unit-tests/mobile/devices-service.ts
  lib/common/test/unit-tests/stubs.ts
  lib/constants.ts
  lib/declarations.d.ts
  lib/device-sockets/ios/app-debug-socket-proxy-factory.ts
  lib/helpers/livesync-command-helper.ts
  lib/services/android-device-debug-service.ts
  lib/services/ios-device-debug-service.ts
  lib/services/ios-log-filter.ts
  lib/services/livesync/android-device-livesync-service.ts
  lib/services/livesync/android-device-livesync-sockets-service.ts
  lib/services/livesync/ios-device-livesync-service.ts
  lib/services/livesync/platform-livesync-service-base.ts
  lib/services/log-source-map-service.ts
  npm-shrinkwrap.json
  package.json
  test/files/sourceMapBundle/android/app/bundle.js
  test/files/sourceMapBundle/ios/app/bundle.js
  test/ios-project-service.ts
  test/services/livesync/android-device-livesync-service-base.ts
  test/services/log-source-map-service.ts
Labels: cla: yes

#4739 refactor: update command
  docs/man_pages/project/configuration/update.md
  lib/bootstrap.ts
  lib/commands/migrate.ts
  lib/commands/update.ts
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/device-platforms-constants.ts
  lib/common/mobile/mobile-helper.ts
  lib/constants.ts
  lib/controllers/migrate-controller.ts
  lib/controllers/update-controller-base.ts
  lib/controllers/update-controller.ts
  lib/declarations.d.ts
  lib/definitions/migrate.d.ts
  lib/definitions/platform.d.ts
  lib/definitions/plugins.d.ts
  lib/definitions/project.d.ts
  lib/definitions/update.d.ts
  lib/helpers/bundle-validator-helper.ts
  lib/package-installation-manager.ts
  lib/package-manager.ts
  lib/services/platform/add-platform-service.ts
  lib/services/plugins-service.ts
  lib/services/project-data-service.ts
  test/controllers/update-controller.ts
  test/stubs.ts
  test/update.ts
Labels: cla: yes

#4753 fix: pass the max_old_space_size option to nodejs, not webpack
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4747 fix: try HMR refresh only when all emitted files are hot updates
  lib/controllers/prepare-controller.ts
  lib/controllers/run-controller.ts
  lib/services/webpack/webpack-compiler-service.ts
  lib/services/webpack/webpack.d.ts
  test/controllers/prepare-controller.ts
Labels: cla: yes

#4754 fix: update the migrate versions to newer ones
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4757 fix: fix run command when no platform is provided
  lib/controllers/prepare-controller.ts
  lib/services/webpack/webpack-compiler-service.ts
Labels: cla: yes

#4756 fix: warnings for Node.js version should be shown once
  lib/common/verify-node-version.ts
Labels: bug, cla: yes

#4758 Kddimitrov/fix log split
  lib/services/log-source-map-service.ts
  test/services/log-source-map-service.ts
Labels: cla: yes

#4759 fix(migrate): do not delete the tns tsconfig for shared apps as it contains a lot of custom code.
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4763 feat: migrate unit test related dependencies so `tns test` command can work out of the box with CLI v6.0
  lib/constants.ts
  lib/controllers/migrate-controller.ts
  lib/controllers/update-controller-base.ts
  lib/definitions/migrate.d.ts
Labels: cla: yes

#4761 fix: device logs are parsed slowly
  lib/common/definitions/mobile.d.ts
  lib/common/mobile/android/android-application-manager.ts
  lib/common/mobile/application-manager-base.ts
  lib/common/mobile/device-log-emitter.ts
  lib/common/mobile/device-log-provider-base.ts
  lib/common/mobile/device-log-provider.ts
  lib/common/mobile/ios/device/ios-application-manager.ts
  lib/common/mobile/ios/simulator/ios-simulator-application-manager.ts
  lib/common/test/unit-tests/mobile/application-manager-base.ts
  lib/common/test/unit-tests/stubs.ts
  lib/services/livesync/platform-livesync-service-base.ts
  lib/services/log-source-map-service.ts
  test/services/log-source-map-service.ts
Labels: bug, cla: yes, device logs

#4668 feat(yarn): yarn support for workspaces
  lib/services/plugins-service.ts
Labels: cla: yes

#4767 fix: fix test command with `--debug-brk` option
  lib/commands/test.ts
Labels: cla: yes

#4771 fix: fix the execution of hooks when there is unresolved injected dependency
  lib/common/services/hooks-service.ts
Labels: cla: yes

#4772 fix: fix publish command
  lib/commands/appstore-upload.ts
  lib/definitions/build.d.ts
  lib/services/ios-project-service.ts
Labels: cla: yes

#4768 feat: remove the auto-generated js, js.map and css files during app migration
  lib/common/definitions/minimatch.d.ts
  lib/controllers/migrate-controller.ts
  npm-shrinkwrap.json
  package.json
  yarn.lock
Labels: cla: yes

#4769 fix: dependency won't be migrated if in devDependencies
  lib/controllers/migrate-controller.ts
  lib/controllers/update-controller-base.ts
  lib/controllers/update-controller.ts
  lib/definitions/plugins.d.ts
  lib/services/plugins-service.ts
Labels: cla: yes

#4766 fix: fix native change during livesync
  lib/controllers/run-controller.ts
  lib/definitions/livesync.d.ts
  lib/services/livesync/ios-livesync-service.ts
  lib/services/livesync/platform-livesync-service-base.ts
Labels: cla: yes

#4773 fix: fix multiple installation on android device
  lib/bootstrap.ts
  lib/controllers/prepare-controller.ts
  lib/controllers/run-controller.ts
  lib/declarations.d.ts
  lib/services/android-plugin-build-service.ts
  lib/services/watch-ignore-list-service.ts
  test/controllers/prepare-controller.ts
  test/services/android-plugin-build-service.ts
Labels: cla: yes

#4774 fix: debug android --start should allow to debug
  lib/commands/debug.ts
Labels: bug, cla: yes, debug

#4775 fix: hmr is working slowly
  lib/controllers/run-controller.ts
Labels: cla: yes, no-changelog

#4776 fix: respect --provision on deploy command
  lib/helpers/deploy-command-helper.ts
  lib/services/log-source-map-service.ts
Labels: cla: yes

#4777 fix: migrate tns-platform-declarations as well
  lib/controllers/migrate-controller.ts
Labels: cla: yes

#4778 fix: fix "Could not open file Library/Application Support/LiveSync/app/tns_modules/tns-core-modules/inspector_modules.js for writing" error on iOS device when hmr fails
  lib/services/livesync/ios-livesync-service.ts
Labels: cla: yes

#4782 fix: exit publish command after uploading package to appstore
  lib/commands/appstore-upload.ts
Labels: cla: yes

#4779 Kddimitrov/fix hanging webpack process
  lib/bash-scripts/terminateProcess.sh
  lib/controllers/prepare-controller.ts
  lib/controllers/run-controller.ts
  lib/definitions/cleanup-service.d.ts
  lib/definitions/prepare.d.ts
  lib/services/cleanup-service.ts
  lib/services/webpack/webpack-compiler-service.ts
  lib/services/webpack/webpack.d.ts
Labels: cla: yes

#4783 chore: merge release in master
  CHANGELOG.md
  lib/common/mobile/ios/device/ios-device.ts
  lib/common/mobile/ios/ios-device-base.ts
  lib/common/mobile/ios/simulator/ios-simulator-device.ts
Labels: cla: yes
